trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, AWS!
  displayName: 'Run a one-line script'

# init -backend
- task: TerraformTaskV3@3
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'bs-aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-crepic21-bs123'
    backendAWSKey: 'kubernetes-dev.tfstate'
# apply
# - task: TerraformTaskV3@3
#   inputs:
#     provider: 'aws'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
#     environmentServiceNameAWS: 'bs-aws-for-terraform'
- task: TerraformTaskV3@3
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'